---

- name: install dependencies
  homebrew: name={{item}} state=latest
  with_items:
    - git
    - git-extras

- name: put up a gitconfig
  become: yes
  copy:
    src: "gitconfig"
    dest: "/etc/gitconfig"

- name: put up a gitconfig
  copy:
    src: "gitconfig"
    dest: "/usr/local/etc/gitconfig"

# set git user name
- name: get git user name
  shell: git config --global --get user.name
  register: git_user_name_result
  changed_when: no
  ignore_errors: yes
- name: set git use rname
  shell: git config --global user.name "{{git_user_name}}"
  when: git_user_name_result.stdout != git_user_name

# set git user email
- name: get git user email
  shell: git config --global --get user.email
  register: git_user_email_result
  changed_when: no
  ignore_errors: yes
- name: set git user email
  shell: git config --global user.email "{{git_user_email}}"
  when: git_user_email_result.stdout != git_user_email
