---

- name: install dependencies
  homebrew:
    state: latest
    name:
      - git
      - git-extras

- name: put up a gitconfig
  become: yes
  copy:
    src: "gitconfig"
    dest: "/etc/gitconfig"

- name: put up a gitconfig
  copy:
    src: "gitconfig"
    dest: "/usr/local/etc/gitconfig"

# set git user
- name: set git user name
  shell: git config --global user.name "{{git_user_name}}"
  changed_when: no
- name: set git user email
  shell: git config --global user.email "{{git_user_email}}"
  changed_when: no
